"""
Russian tag mapping.

The value names emitted here are not free choices: `InflectionsTable` looks cells
up by exact value (``{CASE: "NOM", NUMBER: "SING"}``), and the label maps in
`src/lib/feature-labels.ts` translate those values for display. They therefore
mirror the enum member names in `lambda/inflections-ru/inflections/domain/feature.py`
so that a paradigm assembled from Wiktionary and one generated by pymorphy3 are
interchangeable.

One inherited quirk is worth stating plainly: grammr calls the instrumental
``ABL`` and the prepositional ``LOC``, and `CASE_VALUE_LABELS` maps them back to
"Instrumental" and "Prepositional". The mapping below follows that, rather than
the tag names Wiktionary uses.
"""

from .base import (
    EXCLUDED_FROM_CELLS,
    PLACEHOLDER_FORMS,
    Feature,
    MappedForm,
    normalise,
    strip_accents,
)

CASE_TAGS = {
    "nominative": "NOM",
    "genitive": "GEN",
    "dative": "DAT",
    "accusative": "ACC",
    "instrumental": "ABL",
    "prepositional": "LOC",
    "locative": "LOC",
    "partitive": "PART",
    "vocative": "VOC",
}

NUMBER_TAGS = {
    "singular": "SING",
    "plural": "PLUR",
}

GENDER_TAGS = {
    "masculine": "MASC",
    "feminine": "FEM",
    "neuter": "NEUT",
}

PERSON_TAGS = {
    "first-person": "FIRST",
    "second-person": "SECOND",
    "third-person": "THIRD",
}

TENSE_TAGS = {
    "present": "PRES",
    "past": "PAST",
    "future": "FUT",
}

#: Tag vocabulary for a cell coordinate, keyed by the feature type it produces.
CELL_TAGS: dict[str, dict[str, str]] = {
    "CASE": CASE_TAGS,
    "NUMBER": NUMBER_TAGS,
    "GENDER": GENDER_TAGS,
    "PERSON": PERSON_TAGS,
    "TENSE": TENSE_TAGS,
}

#: Head-word tags that classify the whole lexeme rather than one form, and so
#: belong on `Paradigm.lemmaFeatures`. Gender for nouns is the case the model was
#: built around; animacy and aspect are the two other inherent features
#: `docs/dsl.md` names, and both are present in Wiktionary head tags.
INHERENT_TAGS: dict[str, tuple[str, str]] = {
    "masculine": ("GENDER", "MASC"),
    "feminine": ("GENDER", "FEM"),
    "neuter": ("GENDER", "NEUT"),
    "animate": ("ANIMACY", "ANIM"),
    "inanimate": ("ANIMACY", "INAN"),
    "perfective": ("ASPECT", "PERF"),
    "imperfective": ("ASPECT", "IMPF"),
}

#: Head tags that say the lexeme has no paradigm at all. Kept as a feature so the
#: entry can say so explicitly instead of just showing an empty table -- an
#: indeclinable noun like ``кофе`` is a different thing from a noun whose table
#: failed to extract.
INDECLINABLE_TAGS = frozenset({"indeclinable"})

#: Parts of speech whose gender is inherent rather than inflectional. For
#: adjectives gender is a paradigm dimension, so a head tag naming a gender is
#: describing the lemma's citation form and must not become a `lemmaFeature`;
#: `68c61a8` drew exactly this distinction and the artifact has to respect it.
POS_WITH_INHERENT_GENDER = frozenset({"NOUN", "PROPN"})

#: Same vocabulary as `INHERENT_TAGS`, keyed by the suffix of a wiktextract
#: category name instead of a head tag. Most entries carry gender, animacy and
#: aspect on the `forms[]` row tagged ``canonical`` -- but not all of them do
#: (``приём`` has no canonical row at all), and the category is there regardless,
#: because it drives Wiktionary's own category pages. Matched by suffix rather
#: than exact string because the prefix is the Wiktionary language name
#: ("Russian"), which the categories list never spells out any other way.
#:
#: Order matters: "inanimate nouns" ends with "animate nouns" as a literal
#: substring, and "imperfective verbs" with "perfective verbs", so the more
#: specific suffix has to be tried first and `category_tags` has to stop at its
#: first match per category, or a single inanimate noun would come back tagged
#: both ways.
CATEGORY_INHERENT_SUFFIXES: dict[str, str] = {
    "inanimate nouns": "inanimate",
    "animate nouns": "animate",
    "masculine nouns": "masculine",
    "feminine nouns": "feminine",
    "neuter nouns": "neuter",
    "imperfective verbs": "imperfective",
    "perfective verbs": "perfective",
}


class RussianTagMapper:
    """Maps one wiktextract Russian entry's tags onto grammr features."""

    language = "ru"

    def category_tags(self, categories: list[str]) -> list[str]:
        """
        Recover head tags from an entry's category names.

        Meant to be unioned with the ``canonical`` form's tags in `build.py`, not
        used alone: categories are the fallback for the entries that have no
        canonical row to carry gender, animacy or aspect at all.
        """
        tags = []
        for category in categories:
            for suffix, tag in CATEGORY_INHERENT_SUFFIXES.items():
                if category.endswith(suffix):
                    tags.append(tag)
                    break
        return tags

    def lemma_features(self, pos: str, tags: list[str]) -> list[Feature]:
        """
        Build `Paradigm.lemmaFeatures` from an entry's head-word tags.

        Order is deliberate and stable (gender, animacy, aspect, then the
        indeclinable marker) because `InflectionsTableHeader` joins these into a
        subtitle in the order it receives them.
        """
        seen: set[tuple[str, str]] = set()
        features: list[Feature] = []

        for tag in tags:
            mapped = INHERENT_TAGS.get(tag)
            if mapped is None:
                continue
            feature_type, value = mapped
            if feature_type == "GENDER" and pos not in POS_WITH_INHERENT_GENDER:
                continue
            if mapped in seen:
                continue
            seen.add(mapped)
            features.append(Feature(feature_type, value))

        if any(tag in INDECLINABLE_TAGS for tag in tags):
            features.append(Feature("OTHER", "INDECLINABLE"))

        order = {"GENDER": 0, "ANIMACY": 1, "ASPECT": 2, "OTHER": 3}
        features.sort(key=lambda f: order.get(f.type, 9))
        return features

    def map_form(self, raw: dict) -> MappedForm | None:
        """
        Map a single ``forms[]`` row, or return ``None`` if it is not a form.

        A row survives only if it has a printable value that is not one of
        wiktextract's placeholders. Whether it counts as a paradigm cell is a
        separate question, answered by `_is_cell`.
        """
        value = (raw.get("form") or "").strip()
        if not value or value in PLACEHOLDER_FORMS:
            return None

        tags = list(raw.get("tags") or [])
        features = self._features_for(tags)
        plain = strip_accents(value)

        return MappedForm(
            form=plain,
            accented=value if value != plain else None,
            norm=normalise(value),
            features=features,
            raw_tags=tags,
            is_cell=self._is_cell(tags, features),
        )

    def _features_for(self, tags: list[str]) -> list[Feature]:
        """
        Translate a form's tags into typed features.

        Unrecognised tags are kept as ``OTHER`` rather than discarded:
        `getOrderedFeatures` filters that type out of display, so keeping them
        costs nothing visually while leaving the artifact self-describing when a
        new tag shows up in a later dump.
        """
        features: list[Feature] = []
        for tag in tags:
            for feature_type, vocabulary in CELL_TAGS.items():
                if tag in vocabulary:
                    features.append(Feature(feature_type, vocabulary[tag]))
                    break
            else:
                if tag not in EXCLUDED_FROM_CELLS:
                    features.append(Feature("OTHER", tag.upper()))

        # Wiktionary tags a singular cell by omission rather than by name: a
        # plural form says so explicitly, but a singular one carries no
        # "singular" tag at all -- only the case (a noun's headline genitive) or
        # the gender (an adjective, which does not distinguish gender in the
        # plural). Without this, such a cell's coordinate lacks NUMBER and can
        # never match the one the declension table -- or the inflection
        # service -- produces for the very same form.
        if (
            any(f.type in ("CASE", "GENDER") for f in features)
            and not any(f.type == "NUMBER" for f in features)
        ):
            features.append(Feature("NUMBER", "SING"))

        return features

    @staticmethod
    def _is_cell(tags: list[str], features: list[Feature]) -> bool:
        """
        Decide whether a form addresses a coordinate in a rendered grid.

        Two conditions, both necessary. The row must carry no tag that puts it
        outside the grid (see `EXCLUDED_FROM_CELLS`), and it must actually pin
        down a coordinate -- a form tagged only ``["colloquial"]`` maps to a lone
        ``OTHER`` feature and would otherwise be free to win any cell lookup.
        """
        if any(tag in EXCLUDED_FROM_CELLS for tag in tags):
            return False
        return any(f.type in CELL_TAGS for f in features)
