version: "3"
tasks:
  start-env:
    desc: Start supabase
    dotenv:
      - supabase/functions/.env.local
    cmds:
      - supabase start
      - supabase functions serve --no-verify-jwt --env-file supabase/functions/.env.local

  stop-env:
    desc: Start supabase
    cmds:
      - supabase stop
      - pkill functions || true

  run:
    desc: Run the development server
    cmds:
      - task: start-env
      - pnpm run dev

  apply:*:
    desc: Apply dev infrastructure changes
    dir: ./terraform/application
    vars:
      ENVIRONMENT: "{{index .MATCH 0}}"
    cmds:
      - terraform init -backend-config=config/{{.ENVIRONMENT}}.hcl -reconfigure
      - terraform apply -var-file=config/{{.ENVIRONMENT}}.tfvars -var-file=config/{{.ENVIRONMENT}}.secret.tfvars

  deploy-functions:
    desc: Deploy supabase edge functions
    cmds:
      - supabase secrets set --env-file supabase/functions/.env.local
      - supabase functions deploy literal-translation --no-verify-jwt
      - supabase functions deploy phrase-translation --no-verify-jwt

  build:
    desc: Run formatter, linter, and tests
    cmds:
      - pnpm run fmt
      - pnpm run lint
      - pnpm run build
