version: "3"
tasks:
  start-env:
    desc: Start supabase
    cmds:
      - supabase start --exclude storage-api,mailpit,edge-runtime,vector

  stop-env:
    desc: Start supabase
    cmds:
      - supabase stop
      - pkill functions || true

  run:
    desc: Run the development server
    cmds:
      - task: start-env
      - pnpm run dev

  apply:*:
    desc: Apply dev infrastructure changes
    dir: ./terraform/application
    vars:
      ENVIRONMENT: "{{index .MATCH 0}}"
    cmds:
      - terraform init -backend-config=config/{{.ENVIRONMENT}}.hcl -reconfigure
      - terraform apply -var-file=config/{{.ENVIRONMENT}}.tfvars -var-file=config/secrets.tfvars

  build:
    desc: Run formatter, linter, and tests
    cmds:
      - pnpm run fmt
      - pnpm run lint:fix
      - pnpm run lint
      - pnpm run test
      - pnpm run build
