vercel_source_branch     = "dev"
app_domain               = "dev.grammr.app"
zone_id                  = "fe0c8417e8c4c53f1806fca1bc09017c"
supabase_project_url     = "https://wgngrrmngatubjsilhbj.supabase.co"
supabase_publishable_key = "sb_publishable_lpFzYUt6e8OxbLQNPG4SIw_rf2MYDFq"
